# Found Multiple items
DEPARTMENTS_FOUND_MSG = "Departments found"
CITIES_FOUND_MSG = "Cities found"
USERS_FOUND_MSG = "Users found"
INCOMES_FOUND_MSG = "Incomes found"
LOANS_FOUND_MSG = "Loan found"
EXPENDITURES_FOUND_MSG = "Expenditures found"
SAVINGS_FOUND_MSG = "Savings found"
DSAVINGS_FOUND_MSG = "Defaualt Savings found"
PLANS_FOUND_MSG = "Plans found"
TARGETS_FOUND_MSG = "Targets found"
DEVICES_FOUND_MSG = "Devices found"
DEBTS_FOUND_MSG = "Debts found"
BANKS_FOUND_MSG = "Banks found"
FinancialBucket_FOUND_MSG = "financial_bucket found"
# Found one item
USER_FOUND_MSG = "User found"
INCOME_FOUND_MSG = "Income found"
LOAN_FOUND_MSG = "Loan found"
EXPENDITURE_FOUND_MSG = "Expenditure found"
SAVING_FOUND_MSG = "Saving found"
DSAVING_FOUND_MSG = "Default Saving found"
PLAN_FOUND_MSG = "Plan found"
TARGET_FOUND_MSG = "Target found"
DEVICE_FOUND_MSG = "Device found"
DEBT_FOUND_MSG = "Debt found"
BANK_FOUND_MSG = "Bank found"

# Create item
USER_CREATED_MSG = "User created"
INCOME_CREATED_MSG = "Income created"
LOAN_CREATED_MSG = "Loan created"
EXPENDITURE_CREATED_MSG = "Expenditure created"
SAVING_CREATED_MSG = "Saving created"
DSAVING_CREATED_MSG = "Default Saving created"
PLAN_CREATED_MSG = "Plan created"
PLAN_DETAIL_CREATED_MSG = "Plan detail created"
TARGET_CREATED_MSG = "Target created"
DEVICE_CREATED_MSG = "Device created"
DEBT_CREATED_MSG = "Debt created"
BANK_CREATED_MSG = "Bank created"
FinancialBucket_CREATED_MSG = "financial_bucket created"

# Not found item
USER_NOT_FOUND_MSG = "User not found"
INCOME_NOT_FOUND_MSG = "Income not found"
LOAN_NOT_FOUND_MSG = "Loan not found"
EXPENDITURE_NOT_FOUND_MSG = "Expenditure not found"
SAVING_NOT_FOUND_MSG = "Saving not found"
DSAVING_NOT_FOUND_MSG = "Default Saving not found"
PLAN_NOT_FOUND_MSG = "Plan not found"
TARGET_NOT_FOUND_MSG = "Target not found"
DEVICE_NOT_FOUND_MSG = "Device not found"
DEBT_NOT_FOUND_MSG = "Debt not found"
BANK_NOT_FOUND_MSG = "Bank not found"
FinancialBucket_NOT_FOUND_MSG = "financial_bucket not found"
# Update item
USER_UPDATED_MSG = "User updated"
INCOME_UPDATED_MSG = "Income updated"
LOAN_UPDATED_MSG = "Loan updated"
EXPENDITURE_UPDATED_MSG = "Expenditure updated"
SAVING_UPDATED_MSG = "Saving updated"
DSAVING_UPDATED_MSG = "Default Saving updated"
PLAN_UPDATED_MSG = "Plan updated"
TARGET_UPDATED_MSG = "Target updated"
DEVICE_UPDATED_MSG = "Device updated"
DEBT_UPDATED_MSG = "Debt updated"
BANK_UPDATED_MSG = "Bank updated"

# Delete item
USER_DELETED_MSG = "User deactivated"
INCOME_DELETED_MSG = "Income deleted"
LOAN_DELETED_MSG = "Loan deleted"
EXPENDITURE_DELETED_MSG = "Expenditure deleted"
SAVING_DELETED_MSG = "Saving deleted"
DSAVING_DELETED_MSG = "Default Saving deleted"
PLAN_DELETED_MSG = "Plan deleted"
TARGET_DELETED_MSG = "Target deleted"
DEVICE_DELETED_MSG = "Device deleted"
DEBT_DELETED_MSG = "Debt deleted"
BANK_DELETED_MSG = "Bank deleted"
FinancialBucket_DELETED_MSG = "financial_bucket item deleted"


# Invalid credentials
INVALID_CREDENTIALS_MSG = "Invalid credentials"
INACTIVE_USER_MSG = "Inactive user"
